name: branch_push
on:
  # trigger for all push to feature branches
  push: 
    branches-ignore: [ master ]
    paths-ignore: "**/.md"

jobs: 
  print-vars: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print variables
        run: |
          echo ${{ github.head.ref }}
          echo ${{ github.base.ref }}

  code-check: 
    uses: ./.github/workflows/use-code-check.yml

