name: branch_push
on:
  pull_request: 
    branch: [ master ]
    paths-ignore: "**/.md"

jobs: 
  code-check: 
    uses: ./.github/workflows/use-code-check.yml

  build: 
    needs: code-check
    uses: ./.github/workflows/use-docker-build-push.yml

