name: main-containerize-deploy
on:
  # trigger on merge to master and direct push to master
  push: 
    branches: [ master ]
    paths-ignore: "**/.md"

jobs: 
  code-check: 
    uses: ./.github/workflows/use-code-check.yml

  containerize: 
    needs: code-check
    uses: ./.github/workflows/use-docker-build-push.yml
    secrets: inherit

  deploy: 
    runs-on: ubuntu-latest
    steps: 
      - name: 'Pull from docker and run/deploy'
        run: echo TODO

