name: main_build
on:
  # trigger on merge to master and direct push to master
  push: 
    branches: [ master ]
    paths-ignore: "**/.md"

jobs: 
  print-vars: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print variables
        run: |
          echo ${{ github.head.ref }}
          echo ${{ github.base.ref }}

  code-check: 
    uses: ./.github/workflows/use-code-check.yml

  build: 
    needs: code-check
    uses: ./.github/workflows/use-docker-build-push.yml
    secrets: inherit

