name: merge_ready
on:
  pull_request: 
    branches: [ master ]
    paths-ignore: "**/.md"
  # trigger for all feature branch push
  push: 
    branches-ignore: [ master ]
    paths-ignore: "**/.md"

jobs: 
  code-check: 
    uses: ./.github/workflows/use-code-check.yml

