name: merge_ready
on:
  pull_request: 
    branches: [ master ]
    paths-ignore: "**/.md"

concurrency: 
  group: merge-ready--${{ inputs.head_ref }}

jobs: 

  code-check: 
    uses: ./.github/workflows/use-code-check.yml





