name: Run Tests

on:
  push:
    paths:
      - src/**
      - test/**
      - .github/workflows/run-tests.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}

jobs:
  run-test-cases:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

      # Install only from package.lock.json
      - name: Install Dependencies
        run: npm ci

      - name: Run Unit Test
        run: npm run test

      - name: Run Functional Test
        run: npm run functional-test
