name: code-check lint, unit test

on: workflow_call

concurrency: 
  group: code-check-${{ github.ref_name }}

jobs: 
  print-vars: 
    runs-on: ubuntu-latest
    steps: 
      - name: Print variables
        run: |
          echo ${{ github.head_ref }}
          echo ${{ github.base_ref }}
          echo ${{ github.ref_name }}
          echo ${{ github.ref_name }}
  test: 
    runs-on: ubuntu-latest
    environment: test
    steps: 
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3

        # Install only from package.lock.json
      - name: Install Dependencies 
        run: npm ci

      - name: Run Unit tests
        run:  npm run test

      - name: Build App
        run:  npm run build

