name: Docker build and publish

on: push

jobs:
  # docker_build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v2

  #     - name: Login to Docker Hub
  #       uses: docker/login-action@v2
  #       with:
  #         username: ${{ secrets.DOCKERHUB_USERNAME }}
  #         password: ${{ secrets.DOCKERHUB_TOKEN }}

  #     - name: Build and push
  #       uses: docker/build-push-action@v4
  #       with:
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         tags: ${{ secrets.DOCKERHUB_USERNAME}}/learn:${{ github.sha }}

  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker_build
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions-hub/kubectl@master
  #       env:
  #         KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
  #       with:
  #         args: apply -f manifests

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # - id: update-image
      #   uses: Charlyzzz/update-k8s-image
      #   with:
      #     manifest-path: manifests/deployment.yaml
      #     new-image-tag: ${{ secrets.DOCKERHUB_USERNAME}}/learn:${{ github.sha }}
      #     container-name: react-starter-vite

      - name: Print
        run: cat manifest/deployment.yaml
